name: yas_martix
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.6.2
  lottie: ^3.3.2
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # -------------  Local Assets  ------------- #
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/lottie/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/banners/

  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Meduim.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/t-store-splash-logo-black.png
  image_dark: assets/logos/t-store-splash-logo-white.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/t-store-splash-logo-black.png
    image_dark: assets/logos/t-store-splash-logo-white.png

  web: false
