name: yas_martix
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # -------------  Local Assets  ------------- #
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/

  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Meduim.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
